import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: {
        xl: "90em",
      },
    },
    extend: {
      borderRadius: {
        DEFAULT: "var(--mantine-radius-default)",
        xs: "var(--mantine-radius-xs)",
        sm: "var(--mantine-radius-sm)",
        md: "var(--mantine-radius-md)",
        lg: "var(--mantine-radius-lg)",
        xl: "var(--mantine-radius-xl)",
      },
      boxShadow: {
        focus:
          "0 0 0 4px rgba(var(--mantine-tailwind-raw-primary-color-5), .1)",
        "focus-error":
          "0 0 0 4px rgba(var(--mantine-tailwind-raw-red-color-5), .1)",
      },
      colors: {
        dark: {
          DEFAULT: "rgb(var(--mantine-tailwind-dark-color-default))",
          0: "rgb(var(--mantine-tailwind-dark-color-0))",
          1: "rgb(var(--mantine-tailwind-dark-color-1))",
          2: "rgb(var(--mantine-tailwind-dark-color-2))",
          3: "rgb(var(--mantine-tailwind-dark-color-3))",
          4: "rgb(var(--mantine-tailwind-dark-color-4))",
          5: "rgb(var(--mantine-tailwind-dark-color-5))",
          6: "rgb(var(--mantine-tailwind-dark-color-6))",
          7: "rgb(var(--mantine-tailwind-dark-color-7))",
          8: "rgb(var(--mantine-tailwind-dark-color-8))",
          9: "rgb(var(--mantine-tailwind-dark-color-9))",
        },
        gray: {
          DEFAULT: "rgb(var(--mantine-tailwind-gray-color-default))",
          0: "rgb(var(--mantine-tailwind-gray-color-0))",
          1: "rgb(var(--mantine-tailwind-gray-color-1))",
          2: "rgb(var(--mantine-tailwind-gray-color-2))",
          3: "rgb(var(--mantine-tailwind-gray-color-3))",
          4: "rgb(var(--mantine-tailwind-gray-color-4))",
          5: "rgb(var(--mantine-tailwind-gray-color-5))",
          6: "rgb(var(--mantine-tailwind-gray-color-6))",
          7: "rgb(var(--mantine-tailwind-gray-color-7))",
          8: "rgb(var(--mantine-tailwind-gray-color-8))",
          9: "rgb(var(--mantine-tailwind-gray-color-9))",
        },
        red: {
          DEFAULT: "rgb(var(--mantine-tailwind-red-color-default))",
          0: "rgb(var(--mantine-tailwind-red-color-0))",
          1: "rgb(var(--mantine-tailwind-red-color-1))",
          2: "rgb(var(--mantine-tailwind-red-color-2))",
          3: "rgb(var(--mantine-tailwind-red-color-3))",
          4: "rgb(var(--mantine-tailwind-red-color-4))",
          5: "rgb(var(--mantine-tailwind-red-color-5))",
          6: "rgb(var(--mantine-tailwind-red-color-6))",
          7: "rgb(var(--mantine-tailwind-red-color-7))",
          8: "rgb(var(--mantine-tailwind-red-color-8))",
          9: "rgb(var(--mantine-tailwind-red-color-9))",
        },
        pink: {
          DEFAULT: "rgb(var(--mantine-tailwind-pink-color-default))",
          0: "rgb(var(--mantine-tailwind-pink-color-0))",
          1: "rgb(var(--mantine-tailwind-pink-color-1))",
          2: "rgb(var(--mantine-tailwind-pink-color-2))",
          3: "rgb(var(--mantine-tailwind-pink-color-3))",
          4: "rgb(var(--mantine-tailwind-pink-color-4))",
          5: "rgb(var(--mantine-tailwind-pink-color-5))",
          6: "rgb(var(--mantine-tailwind-pink-color-6))",
          7: "rgb(var(--mantine-tailwind-pink-color-7))",
          8: "rgb(var(--mantine-tailwind-pink-color-8))",
          9: "rgb(var(--mantine-tailwind-pink-color-9))",
        },
        grape: {
          DEFAULT: "rgb(var(--mantine-tailwind-grape-color-default))",
          0: "rgb(var(--mantine-tailwind-grape-color-0))",
          1: "rgb(var(--mantine-tailwind-grape-color-1))",
          2: "rgb(var(--mantine-tailwind-grape-color-2))",
          3: "rgb(var(--mantine-tailwind-grape-color-3))",
          4: "rgb(var(--mantine-tailwind-grape-color-4))",
          5: "rgb(var(--mantine-tailwind-grape-color-5))",
          6: "rgb(var(--mantine-tailwind-grape-color-6))",
          7: "rgb(var(--mantine-tailwind-grape-color-7))",
          8: "rgb(var(--mantine-tailwind-grape-color-8))",
          9: "rgb(var(--mantine-tailwind-grape-color-9))",
        },
        violet: {
          DEFAULT: "rgb(var(--mantine-tailwind-violet-color-default))",
          0: "rgb(var(--mantine-tailwind-violet-color-0))",
          1: "rgb(var(--mantine-tailwind-violet-color-1))",
          2: "rgb(var(--mantine-tailwind-violet-color-2))",
          3: "rgb(var(--mantine-tailwind-violet-color-3))",
          4: "rgb(var(--mantine-tailwind-violet-color-4))",
          5: "rgb(var(--mantine-tailwind-violet-color-5))",
          6: "rgb(var(--mantine-tailwind-violet-color-6))",
          7: "rgb(var(--mantine-tailwind-violet-color-7))",
          8: "rgb(var(--mantine-tailwind-violet-color-8))",
          9: "rgb(var(--mantine-tailwind-violet-color-9))",
        },
        indigo: {
          DEFAULT: "rgb(var(--mantine-tailwind-indigo-color-default))",
          0: "rgb(var(--mantine-tailwind-indigo-color-0))",
          1: "rgb(var(--mantine-tailwind-indigo-color-1))",
          2: "rgb(var(--mantine-tailwind-indigo-color-2))",
          3: "rgb(var(--mantine-tailwind-indigo-color-3))",
          4: "rgb(var(--mantine-tailwind-indigo-color-4))",
          5: "rgb(var(--mantine-tailwind-indigo-color-5))",
          6: "rgb(var(--mantine-tailwind-indigo-color-6))",
          7: "rgb(var(--mantine-tailwind-indigo-color-7))",
          8: "rgb(var(--mantine-tailwind-indigo-color-8))",
          9: "rgb(var(--mantine-tailwind-indigo-color-9))",
        },
        blue: {
          DEFAULT: "rgb(var(--mantine-tailwind-blue-color-default))",
          0: "rgb(var(--mantine-tailwind-blue-color-0))",
          1: "rgb(var(--mantine-tailwind-blue-color-1))",
          2: "rgb(var(--mantine-tailwind-blue-color-2))",
          3: "rgb(var(--mantine-tailwind-blue-color-3))",
          4: "rgb(var(--mantine-tailwind-blue-color-4))",
          5: "rgb(var(--mantine-tailwind-blue-color-5))",
          6: "rgb(var(--mantine-tailwind-blue-color-6))",
          7: "rgb(var(--mantine-tailwind-blue-color-7))",
          8: "rgb(var(--mantine-tailwind-blue-color-8))",
          9: "rgb(var(--mantine-tailwind-blue-color-9))",
        },
        cyan: {
          DEFAULT: "rgb(var(--mantine-tailwind-cyan-color-default))",
          0: "rgb(var(--mantine-tailwind-cyan-color-0))",
          1: "rgb(var(--mantine-tailwind-cyan-color-1))",
          2: "rgb(var(--mantine-tailwind-cyan-color-2))",
          3: "rgb(var(--mantine-tailwind-cyan-color-3))",
          4: "rgb(var(--mantine-tailwind-cyan-color-4))",
          5: "rgb(var(--mantine-tailwind-cyan-color-5))",
          6: "rgb(var(--mantine-tailwind-cyan-color-6))",
          7: "rgb(var(--mantine-tailwind-cyan-color-7))",
          8: "rgb(var(--mantine-tailwind-cyan-color-8))",
          9: "rgb(var(--mantine-tailwind-cyan-color-9))",
        },
        teal: {
          DEFAULT: "rgb(var(--mantine-tailwind-teal-color-default))",
          0: "rgb(var(--mantine-tailwind-teal-color-0))",
          1: "rgb(var(--mantine-tailwind-teal-color-1))",
          2: "rgb(var(--mantine-tailwind-teal-color-2))",
          3: "rgb(var(--mantine-tailwind-teal-color-3))",
          4: "rgb(var(--mantine-tailwind-teal-color-4))",
          5: "rgb(var(--mantine-tailwind-teal-color-5))",
          6: "rgb(var(--mantine-tailwind-teal-color-6))",
          7: "rgb(var(--mantine-tailwind-teal-color-7))",
          8: "rgb(var(--mantine-tailwind-teal-color-8))",
          9: "rgb(var(--mantine-tailwind-teal-color-9))",
        },
        green: {
          DEFAULT: "rgb(var(--mantine-tailwind-green-color-default))",
          0: "rgb(var(--mantine-tailwind-green-color-0))",
          1: "rgb(var(--mantine-tailwind-green-color-1))",
          2: "rgb(var(--mantine-tailwind-green-color-2))",
          3: "rgb(var(--mantine-tailwind-green-color-3))",
          4: "rgb(var(--mantine-tailwind-green-color-4))",
          5: "rgb(var(--mantine-tailwind-green-color-5))",
          6: "rgb(var(--mantine-tailwind-green-color-6))",
          7: "rgb(var(--mantine-tailwind-green-color-7))",
          8: "rgb(var(--mantine-tailwind-green-color-8))",
          9: "rgb(var(--mantine-tailwind-green-color-9))",
        },
        lime: {
          DEFAULT: "rgb(var(--mantine-tailwind-lime-color-default))",
          0: "rgb(var(--mantine-tailwind-lime-color-0))",
          1: "rgb(var(--mantine-tailwind-lime-color-1))",
          2: "rgb(var(--mantine-tailwind-lime-color-2))",
          3: "rgb(var(--mantine-tailwind-lime-color-3))",
          4: "rgb(var(--mantine-tailwind-lime-color-4))",
          5: "rgb(var(--mantine-tailwind-lime-color-5))",
          6: "rgb(var(--mantine-tailwind-lime-color-6))",
          7: "rgb(var(--mantine-tailwind-lime-color-7))",
          8: "rgb(var(--mantine-tailwind-lime-color-8))",
          9: "rgb(var(--mantine-tailwind-lime-color-9))",
        },
        yellow: {
          DEFAULT: "rgb(var(--mantine-tailwind-yellow-color-default))",
          0: "rgb(var(--mantine-tailwind-yellow-color-0))",
          1: "rgb(var(--mantine-tailwind-yellow-color-1))",
          2: "rgb(var(--mantine-tailwind-yellow-color-2))",
          3: "rgb(var(--mantine-tailwind-yellow-color-3))",
          4: "rgb(var(--mantine-tailwind-yellow-color-4))",
          5: "rgb(var(--mantine-tailwind-yellow-color-5))",
          6: "rgb(var(--mantine-tailwind-yellow-color-6))",
          7: "rgb(var(--mantine-tailwind-yellow-color-7))",
          8: "rgb(var(--mantine-tailwind-yellow-color-8))",
          9: "rgb(var(--mantine-tailwind-yellow-color-9))",
        },
        orange: {
          DEFAULT: "rgb(var(--mantine-tailwind-orange-color-default))",
          0: "rgb(var(--mantine-tailwind-orange-color-0))",
          1: "rgb(var(--mantine-tailwind-orange-color-1))",
          2: "rgb(var(--mantine-tailwind-orange-color-2))",
          3: "rgb(var(--mantine-tailwind-orange-color-3))",
          4: "rgb(var(--mantine-tailwind-orange-color-4))",
          5: "rgb(var(--mantine-tailwind-orange-color-5))",
          6: "rgb(var(--mantine-tailwind-orange-color-6))",
          7: "rgb(var(--mantine-tailwind-orange-color-7))",
          8: "rgb(var(--mantine-tailwind-orange-color-8))",
          9: "rgb(var(--mantine-tailwind-orange-color-9))",
        },
        primary: {
          DEFAULT: "rgb(var(--mantine-tailwind-primary-color-default))",
          0: "rgb(var(--mantine-tailwind-primary-color-0))",
          1: "rgb(var(--mantine-tailwind-primary-color-1))",
          2: "rgb(var(--mantine-tailwind-primary-color-2))",
          3: "rgb(var(--mantine-tailwind-primary-color-3))",
          4: "rgb(var(--mantine-tailwind-primary-color-4))",
          5: "rgb(var(--mantine-tailwind-primary-color-5))",
          6: "rgb(var(--mantine-tailwind-primary-color-6))",
          7: "rgb(var(--mantine-tailwind-primary-color-7))",
          8: "rgb(var(--mantine-tailwind-primary-color-8))",
          9: "rgb(var(--mantine-tailwind-primary-color-9))",
        },
      },
      fontFamily: {
        sans: "var(--mantine-font-family)",
      },
      fontSize: {
        xs: "var(--mantine-font-size-xs)",
        sm: "var(--mantine-font-size-sm)",
        md: "var(--mantine-font-size-md)",
        lg: "var(--mantine-font-size-lg)",
        xl: "var(--mantine-font-size-xl)",
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: "100%",
          },
        },
      },
      transitionDuration: {
        DEFAULT: "150ms",
      },
    },
    screens: {
      xs: "30em",
      sm: "48em",
      md: "64em",
      lg: "74em",
      xl: "90em",
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("@tailwindcss/typography")],
};
export default config;
