import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript } from "@mantine/core";
import "@mantine/notifications/styles.css";
import "@mantine/core/styles.layer.css";
import Providers from "@/utils/providers";
import { getLocale } from "next-intl/server";
import { ReactNode } from "react";

const firaSans = Fira_Sans({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={firaSans.className}>
        <Providers mantineFontFamily={firaSans.style.fontFamily}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
